version: '3'
services:
  minio:
    image: quay.io/minio/minio
    container_name: backend-minio
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    command: server /data --console-address ":9001"
  redis:
    image: redis:latest
    container_name: backend-redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    container_name: backend-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=skripsi
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  method5-service:
    build:
      context: /services/
      dockerfile: Dockerfile
    image: method5-service
    container_name: method5-service
  backend:
    container_name: backend-siberpunk
    image: backend-siberpunk
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
  frontend:
    container_name: frontend-siberpunk
    image: frontend-siberpunk
    ports:
      - "80:80"
    build:
      context: ../frontend-pre-plagiarism/
      dockerfile: ../frontend-pre-plagiarism/Dockerfile