version: '3'
services:
  minio:
    image: quay.io/minio/minio
    container_name: backend-minio
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    command: server /data --console-address ":9001"
  redis:
    image: redis:latest
    container_name: backend-redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    container_name: backend-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=skripsi
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro